name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm ci

      # Show what needs to be fixed
      - name: Check formatting
        run: npm run format:check

      - name: Run ESLint
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Comment on PR if CI fails
        if: failure()
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            ❌ CI failed due to linting/formatting issues.
            Run these commands locally to fix:
            ```bash
            npm run lint:fix
            npm run format:write
            ```
            Then commit and push the changes.