name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          # This ensures we can push fixes back if needed
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - run: npm ci

      # Auto-fix formatting issues
      - name: Fix formatting
        run: npx prettier . --write

      # Auto-fix linting issues
      - name: Fix linting
        run: npm run lint:fix

      # Check if there are any changes after fixes
      - name: Check for changes
        id: changes
        run: |
          git add .
          git diff --staged --quiet || echo "changes=true" >> $GITHUB_OUTPUT

      # Commit and push fixes if there are any
      - name: Commit fixes
        if: steps.changes.outputs.changes == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "ci: auto-fix formatting and linting issues"
          git push

      # Verify formatting is correct
      - name: Check formatting
        run: npm run format:check

      # Verify linting is correct
      - name: Run ESLint
        run: npm run lint

      # Run tests
      - name: Run tests
        run: npm test

      # If something fails, add a PR comment
      - name: Comment on PR if CI fails
        if: failure()
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            ❌ CI failed.
            Please run `npm run lint:fix && npm run format` locally before pushing again.